import os, sys
from subprocess import call
from datetime import datetime
from time import sleep
host = sys.argv[1]
conf1 = open('./global_configuration/optima_configuration_file.cnf').read()
conf1 = conf1.replace('optima-host', '{0}'.format(host))
conf2 = open('./global_configuration/optima_configuration_file.cnf', 'w')
conf2.write(conf1)
conf2.close()
os.system("ln -rs ./backend/back/models/ ./configuration-parser/AutomationTools/")
os.system("ln -rs ./backend/back/models/ ./configuration-sender/AutomationTools/")
os.system("ln -rs ./backend/back/models/ ./configuration-differ-precheck/AutomationTools/")
os.system("ln -rs ./backend/back/models/ ./configuration-differ-postcheck/AutomationTools/")
os.system("ln -rs ./backend/back/models/ ./configuration-image-loader/AutomationTools/")
os.system("ln -rs ./backend/back/models/ ./abstraction-layer/abstraction_layer/")
os.system("ln -rs ./backend/back/models/ ./notification/notification/")
os.system("ln -rs ./backend/back/models/ ./orchestrator/orchestrator/")
os.system("ln -rs ./backend/back/models/ ./job_manager/job_manager/")
os.system("ln -rs ./backend/back/db.py ./configuration-parser/AutomationTools/")
os.system("ln -rs ./backend/back/db.py ./configuration-sender/AutomationTools/")
os.system("ln -rs ./backend/back/db.py ./configuration-differ-precheck/AutomationTools/")
os.system("ln -rs ./backend/back/db.py ./configuration-differ-postcheck/AutomationTools/")
os.system("ln -rs ./backend/back/db.py ./configuration-image-loader/AutomationTools/")
os.system("ln -rs ./backend/back/db.py ./abstraction-layer/abstraction_layer/")
os.system("ln -rs ./backend/back/db.py ./notification/notification/")
os.system("ln -rs ./backend/back/db.py ./orchestrator/orchestrator/")
os.system("ln -rs ./backend/back/db.py ./job_manager/job_manager/")
os.system("yum install -y yum-utils")
os.system("yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo")
os.system("yum install -y yum-utils device-mapper-persistent-data lvm2")
os.system("yum-config-manager --enable docker-ce-edge")
os.system("yum makecache fast")
os.system("systemctl start docker")
os.system("systemctl enable docker")
os.system("curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose")
os.system("chmod +x /usr/local/bin/docker-compose")
call(["docker", "build", "-t", "basic_centos7", "."])
call(["docker", "build", "-t", "agent", "./agent-image"])
call(["docker", "build", "-t", "consumer", "./consumer-image"])
call(["cp", "./logstash/01-json-template.conf", "/etc/rsyslog.d/"])
call(["cp", "./logstash/60-output.conf", "/etc/rsyslog.d/"])
call(["/usr/local/bin/docker-compose", "up", "-d"])
print "wait ..."
sleep(30)
os.system("docker start $(docker ps -a -q)")
print "wait ..."
sleep(30)
os.system("docker restart optima_back_1")
print "wait ..."
sleep(60)
print "wait ..."
sleep(10)
call(["curl", "-X", "PUT", "http://{}:9200/optima-{}".format(host,datetime.now().date())])
sleep(7)
os.system("docker start optima_notifications_1")
os.system("docker start $(docker ps -a -q)")
print "wait ..."
sleep(10)
os.system("docker restart  optima_back_1")
os.system("docker restart  optima_abstraction_layer_1")
os.system("docker restart  optima_job_manager_1")
os.system("docker restart  optima_configuration-differ-postcheck_1")
os.system("docker restart  optima_configuration-image-loader_1")
os.system("docker restart  optima_configuration-differ-precheck_1")
os.system("docker restart  optima_configuration-sender_1")
os.system("docker restart  optima_configuration-parser_1")
os.system("docker restart  optima_notifications_1")
os.system("docker restart  optima_orchestrator_1")
call(["docker", "exec", "-it", "optima_postgres_1", "runuser", "-l", "postgres", "-c", "psql -d optimadb -f /home/init.sql"])
