#!/usr/bin/env python

RETURN_OK = True
RETURN_KO = False

CONFIGURATION_IMAGE_LOADER_NAME = 'configuration_image_loader'
CONFIGURATION_PARSER_NAME = 'configuration_parser'
CONFIGURATION_SENDER_NAME = 'configuration_sender'
CONFIGURATION_DIFFER_PRECHECK_NAME = 'configuration_differ_precheck'
CONFIGURATION_DIFFER_POSTCHECK_NAME = 'configuration_differ_postcheck'
AGENT_NAME = 'agent'
MAIN_FOLDER = '/opt/AutomationTools'
CFG_FOLDER = MAIN_FOLDER + '/cfg'
LOG_FOLDER = MAIN_FOLDER + '/log'
RESULT_FOLDER = MAIN_FOLDER + '/results'

CONFIGURATION_IMAGE_LOADER_LOG_FILE = LOG_FOLDER + '/' + AGENT_NAME + '.log'
CONFIGURATION_PARSER_LOG_FILE = LOG_FOLDER + '/' + AGENT_NAME + '.log'
CONFIGURATION_SENDER_LOG_FILE = LOG_FOLDER + '/' + AGENT_NAME + '.log'
CONFIGURATION_DIFFER_PRECHECK_LOG_FILE = LOG_FOLDER + '/' + AGENT_NAME + '.log'
CONFIGURATION_DIFFER_POSTCHECK_LOG_FILE = LOG_FOLDER + '/' + AGENT_NAME + '.log'


CONFIGURATION_IMAGE_LOADER_CONFIG_FILE = CFG_FOLDER + '/agent.cnf'
CONFIGURATION_PARSER_CONFIG_FILE = CFG_FOLDER + '/agent.cnf'
CONFIGURATION_SENDER_CONFIG_FILE = CFG_FOLDER + '/agent.cnf'
CONFIGURATION_DIFFER_PRECHECK_CONFIG_FILE = CFG_FOLDER + '/agent.cnf'
CONFIGURATION_DIFFER_POSTCHECK_CONFIG_FILE = CFG_FOLDER + '/agent.cnf'

CONFIGURATION_IMAGE_LOADER_RESULT_FOLDER = RESULT_FOLDER + '/ImageLoader'
CONFIGURATION_PARSER_RESULT_FOLDER = RESULT_FOLDER + '/ConfigurationParser'
CONFIGURATION_SENDER_RESULT_FOLDER = RESULT_FOLDER + '/ConfigurationSender'
CONFIGURATION_DIFFER_PRECHECK_RESULT_FOLDER = RESULT_FOLDER + '/ConfigurationSender'
CONFIGURATION_DIFFER_POSTCHECK_RESULT_FOLDER = RESULT_FOLDER + '/ConfigurationSender'



COMMON_PARAMETERS = ['hostnameList', 'login', 'password']

AUTOMATION_MANDATORY_PARAMETERS = {
CONFIGURATION_IMAGE_LOADER_NAME:['ftpServer', 'ftpPort', 'ftpUser', 'ftpPassword', 'image'],
CONFIGURATION_PARSER_NAME:[],
CONFIGURATION_SENDER_NAME:[],
}


